### ISSUE TITLE
Roma golem is crashing Minecraft

### ISSUE THREAD

**Issue by Tentoshka** [ThreeHundredBugs/roma-in-minecraft-mod#2]
When Roma golem attacks - minecraft crashes
[Crash report](https://pastebin.com/30cJUAMD)

**Comment by Tentoshka** [comment]
#3 Fix

**Comment by vegassor** [comment]
AHAHAHHAHHA

**Comment by vegassor** [comment]
```

**Comment by vegassor** [comment]
```
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.
 
Time: 25.11.2021, 00:20
Description: Ticking entity
 
java.lang.IllegalArgumentException: Can't find attribute minecraft:generic.attack_damage
	at net.minecraft.entity.attribute.DefaultAttributeContainer.require(DefaultAttributeContainer.java:29)
	at net.minecraft.entity.attribute.DefaultAttributeContainer.getValue(DefaultAttributeContainer.java:33)
	at net.minecraft.entity.attribute.AttributeContainer.getValue(AttributeContainer.java:74)
	at net.minecraft.entity.LivingEntity.getAttributeValue(LivingEntity.java:1610)
	at net.minecraft.entity.passive.IronGolemEntity.getAttackDamage(IronGolemEntity.java:193)
	at net.minecraft.entity.passive.IronGolemEntity.tryAttack(IronGolemEntity.java:200)
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.attack(MeleeAttackGoal.java:122)
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.tick(MeleeAttackGoal.java:114)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.tick(PrioritizedGoal.java:60)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.minecraft.entity.ai.goal.GoalSelector.tick(GoalSelector.java:96)
	at net.minecraft.entity.mob.MobEntity.tickNewAi(MobEntity.java:650)
	at net.minecraft.entity.LivingEntity.tickMovement(LivingEntity.java:2215)
	at net.minecraft.entity.mob.MobEntity.tickMovement(MobEntity.java:473)
	at net.minecraft.entity.passive.IronGolemEntity.tickMovement(IronGolemEntity.java:127)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity.java:2000)
	at net.minecraft.entity.mob.MobEntity.tick(MobEntity.java:301)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld.java:533)
	at net.minecraft.world.World.tickEntity(World.java:480)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:347)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:802)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:751)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:85)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:616)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:245)
	at java.base/java.lang.Thread.run(Thread.java:831)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.attribute.DefaultAttributeContainer.require(DefaultAttributeContainer.java:29)
	at net.minecraft.entity.attribute.DefaultAttributeContainer.getValue(DefaultAttributeContainer.java:33)
	at net.minecraft.entity.attribute.AttributeContainer.getValue(AttributeContainer.java:74)
	at net.minecraft.entity.LivingEntity.getAttributeValue(LivingEntity.java:1610)
	at net.minecraft.entity.passive.IronGolemEntity.getAttackDamage(IronGolemEntity.java:193)
	at net.minecraft.entity.passive.IronGolemEntity.tryAttack(IronGolemEntity.java:200)
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.attack(MeleeAttackGoal.java:122)
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.tick(MeleeAttackGoal.java:114)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.tick(PrioritizedGoal.java:60)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.minecraft.entity.ai.goal.GoalSelector.tick(GoalSelector.java:96)
	at net.minecraft.entity.mob.MobEntity.tickNewAi(MobEntity.java:650)
	at net.minecraft.entity.LivingEntity.tickMovement(LivingEntity.java:2215)
	at net.minecraft.entity.mob.MobEntity.tickMovement(MobEntity.java:473)
	at net.minecraft.entity.passive.IronGolemEntity.tickMovement(IronGolemEntity.java:127)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity.java:2000)
	at net.minecraft.entity.mob.MobEntity.tick(MobEntity.java:301)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld.java:533)
 
-- Entity being ticked --
Details:
	Entity Type: roma_in_minecraft:roma_golem (studymod.tentoshka.entities.roma_golem.RomaGolemEntity)
	Entity ID: 48
	Entity Name: entity.roma_in_minecraft.roma_golem
	Entity's Exact location: -24.85, 66.41, -301.63
	Entity's Block location: World: (-25,66,-302), Chunk: (at 7,4,2 in -2,-19; contains blocks -32,0,-304 to -17,255,-289), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.22, -0.52, -0.03
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.entity.Entity.toString()" because the return value of "net.minecraft.entity.Entity.getVehicle()" is null
Stacktrace:
	at net.minecraft.world.World.tickEntity(World.java:480)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld.java:347)
 
-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Player399'/149, l='ServerLevel[Новый мир]', x=-25.07, y=66.20, z=-303.90]]
	Chunk stats: ServerChunkCache: 2253
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,90,-256), Chunk: (at 0,5,0 in -2,-16; contains blocks -32,0,-256 to -17,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 13597 game time, 2057 day time
	Level name: Новый мир
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 100094 (now: false), thunder time: 148971 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:802)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:751)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:85)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:616)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:245)
	at java.base/java.lang.Thread.run(Thread.java:831)
 
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.10.60-amd64-desktop
	Java Version: 16.0.2, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Amazon.com Inc.
	Memory: 267486720 bytes (255 MB) / 1201668096 bytes (1146 MB) up to 2065694720 bytes (1970 MB)
	CPUs: 8
	JVM Flags: 0 total; 
	Fabric Mods: 
		fabric: Fabric API 0.42.0+1.16
		fabric-api-base: Fabric API Base 0.4.0+3cc0f0907d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+3cc0f0907d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.13+3cc0f0907d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+3cc0f0907d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+3cc0f0907d
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+3cc0f0907d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+3cc0f0907d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.5+3cc0f0907d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+3cc0f0907d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.8+3cc0f0907d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+3cc0f0907d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.5+3cc0f0907d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+3cc0f0907d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+3cc0f0907d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.2+3cc0f0907d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+3cc0f0907d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+3cc0f0907d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+3cc0f0907d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.2+3cc0f0907d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+3cc0f0907d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+3cc0f0907d
		fabric-models-v0: Fabric Models (v0) 0.3.1+3cc0f0907d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+3cc0f0907d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+3cc0f0907d
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+3cc0f0907d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.6+3cc0f0907d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+3cc0f0907d
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+3cc0f0907d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+3cc0f0907d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+3cc0f0907d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.5+3cc0f0907d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.1+3cc0f0907d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+3cc0f0907d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.15+3cc0f0907d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+3cc0f0907d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.1+3cc0f0907d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+3cc0f0907d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+3cc0f0907d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+3cc0f0907d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+3cc0f0907d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+3cc0f0907d
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+3cc0f0907d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.8+3cc0f0907d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+3cc0f0907d
		fabricloader: Fabric Loader 0.12.5
		java: OpenJDK 64-Bit Server VM 16
		minecraft: Minecraft 1.16.5
		roma_in_minecraft: Roma in Minecraft 1.0-SNAPSHOT
	Player Count: 1 / 8; [ServerPlayerEntity['Player399'/149, l='ServerLevel[Новый мир]', x=-25.07, y=66.20, z=-303.90]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
```
